### PR TITLE
updated LPH, pls merge. 

### PR DESCRIPTION
**Pull request by SophiaW24**

### CODE REVIEW

**Comment by SophiaW24** [comment]
I hope this time I did it correctly.

**Review by galicae — CHANGES_REQUESTED** [review]
Good job with the new fork! Unfortunately you were a bit trigger-happy with the deletions - please re-insert lines 134-136 and then I can merge :)

**Comment by SophiaW24** [comment]
Okay, I reinserted line 134-136. I hope it will work now.

**Review by galicae — APPROVED** [review]
good job!

**Pull request merged**
